spring:
  application:
    name: homework


  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

api:
  v1: ${API_V1}

payment:
  toss:
    secrete-key: ${TOSS_SECRET_KEY:}
    success-url: ${TOSS_SUCCESS_URL:}
    fail-url: ${TOSS_FAIL_URL:}